# Predbat translateor for fox ess inverters
#

input_number:
  force_charge_power_w:
    name: Force Charge Power (watts)
    min: 0
    max: 6000
    step: 1
    unit_of_measurement: W
    
  force_discharge_power_w:
    name: Force Discharge Power (watts)
    min: 0
    max: 6000
    step: 1
    unit_of_measurement: W

automation:
  - alias: "Force Charge Power Translator"
    id: force_charge_power_translator
    triggers:
      - trigger: state
        entity_id: input_number.force_charge_power_w
    actions:
      service: number.set_value
      target:
        entity_id: number.force_charge_power
      data:
        value: "{{ states('input_number.force_charge_power_w')|float / 1000 }}"

  - alias: "Force Disharge Power Translator"
    id: force_discharge_power_translator
    triggers:
      - trigger: state
        entity_id: input_number.force_discharge_power_w
    actions:
      service: number.set_value
      target:
        entity_id: number.force_discharge_power
      data:
        value: "{{ states('input_number.force_discharge_power_w')|float / 1000 }}"
        
sensor:
- platform: template
  sensors:
    bms_actual_kwh_remaining:
            friendly_name: "BMS kWh Remaining (SOH)"
            unique_id: 'foxess_bms_kwh_remaining'
            unit_of_measurement: 'kWh'
            device_class: energy
            value_template: >
              {%- set bms_kwh_remaining = states('sensor.bms_kwh_remaining')|float(default=0)  %}
              {%- set battery_soc = states('sensor.battery_soc')|float(default=0) %}
              {{ (bms_kwh_remaining * battery_soc / 100)|round(3,"floor",0) }}
            availability_template: >
              {{ states('sensor.bms_kwh_remaining')|float(default=0) > 0 and states('sensor.battery_soc')|float(default=0) > 0 }}
              
    pv_power_w:
            friendly_name: "PV Power (Watts)"
            unique_id: 'foxess_pv_power_w'
            unit_of_measurement: "W"
            device_class: power
            value_template: >
                {{ (states('sensor.pv_power') | float(0)) * 1000 }}                                

